# Generated by Django 3.1.4 on 2021-02-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='url',
            new_name='image_url',
        ),
    ]
